# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kelle Clark, Exploring Computer Science and Mathematics
email: clarkke20@students.ecu.edu
description: >- # this means to ignore newlines until "baseurl:"
  A journey, complete with unexpected side-trips, into topics in 
  Computer Science and Mathematics that I find interesting.
baseurl: "/mysite" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kclarkcode
github_username:  KelleClark

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

# Letting Jekyll know where to find the landing page
# similar to $PATH it is an array of directories that 
# Jekyll should search
include: [_pages, _posts]

# Working with YAML metadata and defining variables for 
# the basic "types" of layouts used
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      url: /blog/:title
      permalink: /blog/:title/
     
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

sass:
    style: compressed
    sass_dir: _sass


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
